# Generated by Django 4.1.7 on 2023-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geschenke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geschenk',
            name='description',
        ),
        migrations.AlterField(
            model_name='geschenk',
            name='image',
            field=models.ImageField(blank=True, upload_to='geschenke/bilder/'),
        ),
        migrations.AlterField(
            model_name='geschenk',
            name='url',
            field=models.URLField(),
        ),
    ]
