# Generated by Django 4.1.7 on 2023-05-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geschenke', '0002_remove_geschenk_description_alter_geschenk_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschenk',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
