# Generated by Django 4.1.7 on 2023-05-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geschenke', '0003_geschenk_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geschenk',
            name='image',
        ),
    ]
