# Generated by Django 4.1.7 on 2023-05-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geschenke', '0004_remove_geschenk_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschenk',
            name='image',
            field=models.ImageField(blank=True, upload_to='geschenke/bilder/'),
        ),
    ]
